name = "couvance-ops"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist/client"

[[d1_databases]]
binding = "DB"
database_name = "couvance-ops-db"
database_id = "eaed759c-4051-4cbd-824a-97cff5109e79"
migrations_dir = "drizzle"

